name: etl-deployment

on:
  push:
      branches:
        - main



jobs:
    run-tests:
        name: run-tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo #checkout repo using action
              uses: actions/checkout@v3
            - name: Use Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'
            - name: Install make
              run: sudo apt install make -y
            - name: Install Requirements
              run: make requirements
            - name: Setup dev requirements
              run: make dev-setup
            # - name: Run Checks
            #   run: make run-checks (uncomment when unit tests set up)
    deploy-script:
      needs: run-tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1-node16
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install boto3   
        - name: DEPLOY!
          run: python ./src/deployment.py
     